# Generated by Django 4.2.14 on 2024-07-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_product_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to='service.discount'),
            preserve_default=False,
        ),
    ]
