# Generated by Django 4.2.14 on 2024-07-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_discount_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Discount',
            new_name='discount',
        ),
    ]
