# Generated by Django 4.2.14 on 2024-07-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dicount',
            field=models.OneToOneField(default=100, on_delete=django.db.models.deletion.CASCADE, to='service.discount'),
            preserve_default=False,
        ),
    ]
