# Generated by Django 4.2.14 on 2024-07-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_product_dicount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dicount',
        ),
    ]
